import type { Quote } from "@shared/schema";
import type { QuoteFormFields } from "@/features/quote-calculator/schema";

/**
 * Build a minimal Quote object for tests.
 * Use this to avoid verbose object literals and unsafe casts in tests.
 */
export function makeMinimalQuote(partial: Partial<Quote> = {}): Quote {
  const base = {
    id: 1,
    contactEmail: "test@example.com",
    monthlyRevenueRange: "10k-50k",
    monthlyTransactions: "100-300",
    industry: "Technology",
    cleanupMonths: 0,
    cleanupComplexity: "1.0",
    includesBookkeeping: true,
    includesTaas: false,
    archived: false,
    quoteType: "bookkeeping",
    monthlyFee: "0",
    setupFee: "0",
    serviceMonthlyBookkeeping: true,
    serviceCleanupProjects: false,
    serviceTaasMonthly: false,
    servicePriorYearFilings: false,
    serviceCfoAdvisory: false,
    servicePayrollService: false,
    serviceApArService: false,
    serviceFpaBuild: false,
    serviceFpaSupport: false,
    serviceNexusStudy: false,
    serviceEntityOptimization: false,
    serviceCostSegregation: false,
    serviceRdCredit: false,
    serviceRealEstateAdvisory: false,
    ownerId: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  } as unknown as Quote; // Cast to Quote to keep factory usage ergonomic
  return { ...(base as any), ...(partial as any) } as Quote;
}

/**
 * Build QuoteFormFields with sensible defaults, override via partial.
 */
export function makeFormFields(partial: Partial<QuoteFormFields> = {}): QuoteFormFields {
  const base: QuoteFormFields = {
    contactEmail: "a@example.com",
    companyName: "Acme Co",
    monthlyRevenueRange: "10k-50k",
    monthlyTransactions: "100-300",
    industry: "Technology",
    entityType: "LLC",
    cleanupMonths: 0,
    cleanupComplexity: "1.0",
    overrideReason: "",
    customOverrideReason: "",
    customSetupFee: "",
    quoteType: "bookkeeping",
    serviceMonthlyBookkeeping: true,
    serviceTaasMonthly: false,
    serviceCleanupProjects: false,
    servicePriorYearFilings: false,
    serviceCfoAdvisory: false,
    servicePayrollService: false,
    serviceApArService: false,
    serviceArService: false,
    serviceFpaBuild: false,
    serviceFpaSupport: false,
    serviceNexusStudy: false,
    serviceEntityOptimization: false,
    serviceCostSegregation: false,
    serviceRdCredit: false,
    serviceRealEstateAdvisory: false,
    includesBookkeeping: true,
    includesTaas: false,
    numEntities: 1,
    statesFiled: 1,
    internationalFiling: false,
    numBusinessOwners: 1,
    include1040s: false,
    priorYearsUnfiled: 0,
    qboSubscription: false,
    serviceTier: "Automated",
    accountingBasis: "Accrual",
    businessLoans: false,
    currentBookkeepingSoftware: "QuickBooks Online",
    otherBookkeepingSoftware: "",
    primaryBank: "",
    otherPrimaryBank: "",
    additionalBanks: [],
    otherAdditionalBanks: [],
    merchantProviders: [],
    otherMerchantProvider: "",
    serviceAgentOfService: false,
    agentOfServiceAdditionalStates: 0,
    agentOfServiceComplexCase: false,
    approvalCode: "",
    contactFirstName: "",
    contactLastName: "",
    clientStreetAddress: "",
    clientCity: "",
    clientState: "",
    clientZipCode: "",
    clientCountry: "US",
    companyNameLocked: false,
    contactFirstNameLocked: false,
    contactLastNameLocked: false,
    industryLocked: false,
    companyAddressLocked: false,
    bookkeepingQuality: "Clean (Seed)",
    priorYearFilings: [],
    cleanupPeriods: [],
    apVendorBillsBand: "",
    apVendorCount: 0,
    customApVendorCount: null,
    apServiceTier: "lite",
    arCustomerInvoicesBand: "",
    arCustomerCount: 0,
    customArCustomerCount: null,
    arServiceTier: "advanced",
    cfoAdvisoryType: "",
    cfoAdvisoryBundleHours: 8,
    cfoAdvisoryHubspotProductId: "",
    payrollEmployeeCount: 1,
    payrollStateCount: 1,
  };
  return { ...base, ...partial } as QuoteFormFields;
}
